import {
  Box,
  Button,
  Modal,
  ModalBody,
  ModalCloseButton,
  ModalContent,
  ModalFooter,
  ModalHeader,
  ModalOverlay,
  Text,
  useDisclosure,
} from '@chakra-ui/react';
import Head from 'next/head';

export default function Home() {
  const { isOpen, onOpen, onClose } = useDisclosure();

  return (
    <Box px="2rem">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Text>PDFJS EXPRESS NEXT</Text>

      <Button onClick={onOpen}>Open Modal (PSDPDF EDITOR)</Button>

      <Modal isOpen={isOpen} onClose={onClose} size="6xl">
        <ModalOverlay />
        <ModalContent>
          <ModalHeader>Modal Title</ModalHeader>
          <ModalCloseButton />
          <ModalBody>
            <Text>PDF View</Text>
            <Box height="700px" />
          </ModalBody>

          <ModalFooter>
            <Button colorScheme="blue" mr={3} onClick={onClose}>
              Close
            </Button>
            {/* <Button variant="ghost" onClick={saveToLocal}>
              Save to local
            </Button>
            <Button variant="ghost" onClick={saveToRemoteServer}>
              Save to remote server
            </Button> */}
          </ModalFooter>
        </ModalContent>
      </Modal>
    </Box>
  );
}
